config:
  create_new_custom_role:
    - role_name: "role_name"
      description: "role_description"
      assurance: "deny/read/write"
      network_analytics: "deny/read/write"
      network_design: "deny/read/write"
      network_provision: "deny/read/write"
      network_services: "deny/read/write"
      platform: "deny/read/write"
      security: "deny/read/write"
      system: "deny/read/write"
      utilities: "deny/read/write"

