config:
  role_details:
    - rolename: "Test_Role_1"
      description: "Role_description"
      assurance:
        - monitoring_and_troubleshooting: "read"
          monitoring_settings: "deny"
          troubleshooting_tools: "write"
      network_analytics:
        data_access: "deny/read/write"
      network_design:
        - advanced_network_settings: "deny/read/write"
          image_repository: "deny/read/write"
          network_hierarchy: "deny/read/write"
          network_profiles: "deny/read/write"
          network_settings: "deny/read/write"
          virtual_network: "deny/read/write"
      network_provision:
        - compliance: "deny/read/write"
          image_update: "deny/read/write"
          inventory_management:
            - device_configuration: "deny/read/write"
              discovery: "deny/read/write"
              network_device: "deny/read/write"
              port_management: "deny/read/write"
              topology: "deny/read/write"
          license: "deny/read/write"
          network_telemetry: "deny/read/write"
          pnp: "deny/read/write"
          provision: "deny/read/write"
      network_services:
        - app_hosting: "deny/read/write"
          bonjour: "deny/read/write"
          stealthwatch: "deny/read/write"
          umbrella: "deny/read/write"
      platform:
        - apis: "deny/read/write"
          bundles: "deny/read/write"
          events: "deny/read/write"
          reports: "deny/read/write"
      security:
        - group_based_policy: "deny/read/write"
          ip_based_access_control: "deny/read/write"
          security_advisories: "deny/read/write"
      system:
        - machine_reasoning: "deny/read/write"
          system_management: "deny/read/write"
      utilities:
        - audit_log: "deny/read/write"
          event_viewer: "deny/read/write"
          network_reasoner: "deny/read/write"
          scheduler: "deny/read/write"
          search: "deny/read/write"
