---
- name: Configure device credentials on Cisco DNA Center
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - "input_swim.yml"
    - "credentials.yml"
  tasks:
    - name: Import an image, tag it as golden and load it on device
      cisco.dnac.swim_workflow_manager:
        dnac_host: "{{dnac_host}}"
        dnac_username: "{{dnac_username}}"
        dnac_password: "{{dnac_password}}"
        dnac_verify: "{{dnac_verify}}"
        dnac_port: "{{dnac_port}}"
        dnac_version: "{{dnac_version}}"
        dnac_debug: "{{dnac_debug}}"
        dnac_log: True
        dnac_log_level: DEBUG
        config_verify: True
        dnac_api_task_timeout: 1000
        dnac_task_poll_interval: 1
        config:
        - import_image_details:
            type: "remote"
            url_details:
              payload:
              - source_url: http://172.21.236.183/swim/V1712_2_CCO/cat9k_iosxe.17.12.02.SPA.bin
                third_party: False
          tagging_details:
            image_name: "cat9k_iosxe.17.12.02.SPA.bin"
            device_role: "ALL"
            device_image_family_name: "Cisco Catalyst 9000 UADP 8 Port Virtual Switch"
            site_name: "Global/LTTS/FLOOR1"
            tagging: True
          image_distribution_details:
            image_name: "cat9k_iosxe.17.12.02.SPA.bin"
            device_serial_number: "FOC2225U12L"
          image_activation_details:
            image_name: "cat9k_iosxe.17.12.02.SPA.bin"
            schedule_validate: False
            activate_lower_image_version: False
            distribute_if_needed: True
            device_serial_number: "FOC2225U12L"
